#-------------------------------
# Site Settings
title: 
# logo: '/images/binary_number_networks.png'
author: Dr. Johannes M. Schleicher
description: My personal homepage and mentalflares as a blog. 


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: 'https://www.mentalflares.com'
    - title: 'CV'
      url: '/images/CV_Schleicher_EN_2024.pdf'


#-------------------------------
# Hero Settings
hero:
  hero__title: Hi! 👋 
  hero__description: >
    I'm <strong>Johannes M. Schleicher</strong> – engineer by training, builder by nature, and entrepreneur by conviction. Over the past two decades, I've designed and scaled intelligent software systems across a wide range of domains – from distributed energy infrastructure to smart cities, from AI in healthcare and sports to cloud platforms powering €100M+ in revenue.<br><br>
    I'm the ❤️ and co-founder of <a href="https://www.jademind.com">JadeMind GmbH</a>, a lean, independent and profitable software company I've been running with my friend <a href="https://www.katzian.net">Andreas</a> for over 14 years. Together, we help organizations solve complex problems — simply, fast, and effectively. No bullshit. Just deep tech, clear minds, and focused execution. We do what we love, focus on the essence, and strive for real outcomes.<br><br>
    I've served as CIO and tech lead at <a href="https://www.neoom.com">neoom AG</a>, Austria's leading cleantech company. I helped scale the company from 19 to nearly 300 employees while building a platform that now powers thousands of energy sites across Europe and substantially contributed to €100 million in revenue.<br><br>
    I hold a Ph.D. in Distributed Systems from TU Vienna, where I focused on smart city application ecosystems and received the Austrian Award of Excellence for my dissertation. My <a href="https://scholar.google.com/citations?user=1VGMIxwAAAAJ&hl=en&oi=ao">research</a> has been published in leading journals and cited over 600 times. In 2022, I had the opportunity to share my thoughts on human-centered innovation in a TEDx talk titled <a href="https://www.ted.com/talks/johannes_m_schleicher_small_changes_big_johannes_m_schleicher_tedxtuwien">"Small Changes, Big"</a><br><br>
    Along the way, I've learned that what matters most isn't just what we build – but how and why we build it. I'm passionate about creating tools and systems that support clarity, calm, and better ways of living and working – as a founder, a father of two, and a human being navigating a complex world.<br><br>
    On <a href="https://www.twitter.com/jomisjm">Twitter</a> and our <a href="https://www.mentalflares.com">blog</a>, I share actionable insights on technology, entrepreneurship, health, and intentional living.<br><br>
    Want to connect or collaborate? I'm always open for meaningful conversations, just mail <a mailto="me@jomis.net">me@jomis.net</a>


#-------------------------------
# Portfolio Settings
# portfolio:
#   portfolio__title: Portfolio
#   portfolio__gallery:
#     - image: /images/gallery-01.jpg
#       title: Samantha Gades
#       description: Brown photo frame beside wall <a href="https://unsplash.com/photos/8Od75hgzb9Y">Unsplash</a>

#     - image: /images/gallery-02.jpg
#       title: Paula Vermeulen
#       description: Gray mountain covered by mountain <a href="https://unsplash.com/photos/_f2m3mEkaaU">Unsplash</a>

#     - image: /images/gallery-03.jpg
#       title: Bench Accounting
#       description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>

#     - image: /images/gallery-04.jpg
#       title: Nord Wood
#       description: White ceramic mug <a href="https://unsplash.com/photos/nDd3dIkkOLo">Unsplash</a>

#     - image: /images/gallery-05.jpg
#       title: Luca Bravo
#       description: White ribs in a facade against a white sky <a href="https://unsplash.com/photos/alS7ewQ41M8">Unsplash</a>

#     - image: /images/gallery-06.jpg
#       title: Isaac Benhesed
#       description: Minimalist black coffee <a href="https://unsplash.com/photos/onLbXleIkds">Unsplash</a>

#     - image: /images/gallery-07.jpg
#       title: Water Journal
#       description: Water Journal is a bi-annual publication exploring the beauty and complexity of all things water <a href="https://unsplash.com/photos/EbuaKnSm8Zw">Unsplash</a>

#     - image: /images/gallery-08.jpg
#       title: Luca Bravo
#       description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

#     - image: /images/gallery-09.jpg
#       title: Books and Laptop
#       description: Silver laptop computer with two books on the top <a href="https://unsplash.com/photos/fFIAKABImf4">Unsplash</a>


#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get updates and digital art inspiration # Add your Title
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-twitter", color: "#55acee", label: jomisjm, link: "https://twitter.com/jomisjm"}
- {icon: "ion-logo-github", color: "#24292e", label: jomis, link: "https://github.com/jomis"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contact form
  description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id