#-------------------------------
# Site Settings
title: 
# logo: '/images/binary_number_networks.png'
author: Dr. Johannes M. Schleicher
description: My personal homepage and mentalflares as a blog. 


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: '/blog/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Johannes M. Schleicher, Ph.D.
  hero__description: Hi! I'm a passionate technologist, seasoned entrepreneur, avid explorer and former <a href="https://scholar.google.com/citations?user=1VGMIxwAAAAJ">scientist</a>. I leverage my deep understanding of technology, effective problem-solving, and efficient optimization to create impactful solutions. Currently I serve as the CIO of Austria's leading energy scale-up, <a href="https://www.neoom.com">ne∞m</a>, and CEO and ❤️ of <a href="https://www.jademind.com">JadeMind GmbH</a>.<br><br>I share actionable insights on how I leverage technology in my journey to create impactful solutions, improve health and happiness, and achieve more with less. Follow me on <a href="https://www.twitter.com/jomisjm">Twitter</a> for immediate updates or write <a mailto="me@jomis.net">me@jomis.net</a> for questions.

#-------------------------------
# Portfolio Settings
# portfolio:
#   portfolio__title: Portfolio
#   portfolio__gallery:
#     - image: /images/gallery-01.jpg
#       title: Samantha Gades
#       description: Brown photo frame beside wall <a href="https://unsplash.com/photos/8Od75hgzb9Y">Unsplash</a>

#     - image: /images/gallery-02.jpg
#       title: Paula Vermeulen
#       description: Gray mountain covered by mountain <a href="https://unsplash.com/photos/_f2m3mEkaaU">Unsplash</a>

#     - image: /images/gallery-03.jpg
#       title: Bench Accounting
#       description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>

#     - image: /images/gallery-04.jpg
#       title: Nord Wood
#       description: White ceramic mug <a href="https://unsplash.com/photos/nDd3dIkkOLo">Unsplash</a>

#     - image: /images/gallery-05.jpg
#       title: Luca Bravo
#       description: White ribs in a facade against a white sky <a href="https://unsplash.com/photos/alS7ewQ41M8">Unsplash</a>

#     - image: /images/gallery-06.jpg
#       title: Isaac Benhesed
#       description: Minimalist black coffee <a href="https://unsplash.com/photos/onLbXleIkds">Unsplash</a>

#     - image: /images/gallery-07.jpg
#       title: Water Journal
#       description: Water Journal is a bi-annual publication exploring the beauty and complexity of all things water <a href="https://unsplash.com/photos/EbuaKnSm8Zw">Unsplash</a>

#     - image: /images/gallery-08.jpg
#       title: Luca Bravo
#       description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

#     - image: /images/gallery-09.jpg
#       title: Books and Laptop
#       description: Silver laptop computer with two books on the top <a href="https://unsplash.com/photos/fFIAKABImf4">Unsplash</a>


#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get updates and digital art inspiration # Add your Title
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-twitter", color: "#55acee", label: jomisjm, link: "https://twitter.com/jomisjm"}
- {icon: "ion-logo-github", color: "#24292e", label: jomis, link: "https://github.com/jomis"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contact form
  description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id